import { SearchBar, MovieCard, Sidebar } from '@/components';
import { useContext, useState } from 'react';
import { SiHomeassistant } from 'react-icons/si';
import { GetServerSideProps } from 'next';
import { ThemeContext } from '@/context/themeContext';
import { imgBaseUrl, baseUrl, apiKey } from '@/constants/constants';
import Head from 'next/head';

interface Props {
	id: number;
	firstName: string;
	lastName: string;
	fullName: string;
	family: string;
	imageUrl: string;
	name: string;
	title: string;
	backdrop_path: string;
	media_type: string;
	profile_path: string;
	vote_average: number;
	overview: string;
	first_air_date: string;
	original_language: string;
	known_for_department: string;
	popularity: number;
}

export default function Home({ movies }: { movies: Props[] }) {
	const { theme } = useContext(ThemeContext);

	return (
		<>
			<Head>
				<title>Moflix | Movies | Tv Shows</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Head>
				<title>Moflix | Movies | Tv Shows</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<div className={`container-fluid bg-${theme === 'dark' && 'dark'} `}>
				<div className='row min-vh-100 flex-column flex-md-row '>
					<Sidebar />
					<main className='col px-0 flex-grow-1 position-relative overflow-hidden'>
						{/* SearchBar */}
						<SearchBar />
						{/* Cards */}
						<div className='row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-md-2 row-cols-xl-4 mx-auto p-0 my-3 px-2'>
							{movies?.map((m) => {
								return (
									<MovieCard
										key={m.id}
										title={m.name || m.title}
										imageUrl={imgBaseUrl + '/w300' + m.profile_path}
										type={m.known_for_department}
										chair={m.title}
										id={m.id}
										vote={m.vote_average}
									/>
								);
							})}
						</div>
					</main>
				</div>
			</div>
		</>
	);
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	// Fetch data from external API
	const res = await fetch(`${baseUrl}/person/popular?api_key=${apiKey}`);
	const movies = await res.json();

	return {
		props: { movies: movies.results }, // will be passed to the page component as props
	};
};
