import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Breadcrumb, MovieCard, Sidebar } from '@/components';
import { useContext, useState } from 'react';
import { SiHomeassistant } from 'react-icons/si';
import { GetServerSideProps } from 'next';
import { ThemeContext } from '@/context/themeContext';

interface Props {
	id: number;
	firstName: string;
	lastName: string;
	fullName: string;
	family: string;
	imageUrl: string;
	title: string;
	original_name: string;
	backdrop_path: string;
	media_type: string;
	poster_path: string;
	vote_average: number;
}

// adult
// :
// false
// backdrop_path
// :
// "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg"
// first_air_date
// :
// "2023-01-15"
// genre_ids
// :
// (3) [18, 10765, 10759]
// id
// :
// 100088
// media_type
// :
// "tv"
// name
// :
// "The Last of Us"
// origin_country
// :
// ['US']
// original_language
// :
// "en"
// original_name
// :
// "The Last of Us"
// overview
// :
// "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival."
// popularity
// :
// 7500.029
// poster_path
// :
// "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg"
// vote_average
// :
// 8.917
// vote_count
// :
// 935
export default function Home({ movies }: { movies: Props[] }) {
	const { theme } = useContext(ThemeContext);
	console.log(movies);

	const moviess = [];
	return (
		<>
			<Head>
				<title>Moflix | Movies | Tv Shows</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<div className={`container-fluid bg-${theme === 'dark' && 'secondary'} `}>
				<div className='row min-vh-100 flex-column flex-md-row '>
					<Sidebar />
					<main className='col px-0 flex-grow-1'>
						{/* Breadcrumb */}
						<Breadcrumb />
						{/* Cards */}
						<div className='row row-cols-1 row-cols-sm-2  row-cols-lg-4 row-cols-md-2 g-4 container-fluid mx-auto py-4 overflow-x-auto'>
							{movies?.map((m) => {
								return (
									<MovieCard
										key={m.id}
										title={m.original_name}
										imageUrl={
											process.env.NEXT_PUBLIC_PICTURE_URL + m.poster_path
										}
										badge={m.media_type}
										chair={m.title}
										id={m.id}
										vote={m.vote_average.toFixed(0)}
									/>
								);
							})}
						</div>
					</main>
				</div>
			</div>
		</>
	);
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	// Fetch data from external API
	const res = await fetch(
		`${process.env.NEXT_PUBLIC_BASE_URL}/trending/all/week?api_key=${process.env.NEXT_PUBLIC_API_KEY}`
	);
	const movies = await res.json();

	return {
		props: { movies: movies.results }, // will be passed to the page component as props
	};
};
