import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Header, MovieCard } from '@/components';
import { useState } from 'react';
import { SiHomeassistant } from 'react-icons/si';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const [mode, setmode] = useState('light');
	const toggleMode = () => {
		if (mode === 'light') {
			setmode('dark');
			document.body.style.backgroundColor = '#141a4d';
		} else {
			setmode('light');
			document.body.style.backgroundColor = 'white';
		}
	};
	return (
		<>
			<Head>
				<title>Moflix | Movies | Tv Shows</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main className=''>
				<Header
					mode={mode}
					toggleMode={toggleMode}
				/>
				{/* Breadcrumbs */}
				<div className='row container-fluid mx-auto '>
					<nav
						aria-label='breadcrumb'
						className=' my-2   mx-auto'
					>
						<ol className='breadcrumb'>
							<li className='breadcrumb-item'>
								<a href='#'>
									<SiHomeassistant />
								</a>
							</li>
							<li className='breadcrumb-item'>
								<a href='#'>Movies</a>
							</li>
							<li
								className='breadcrumb-item active'
								aria-current='page'
							>
								Trending
							</li>
						</ol>
					</nav>
				</div>
				{/* Featured */}
				{/* Recent */}
				<div className='row row-cols-1 row-cols-sm-2  row-cols-lg-5 row-cols-md-3 g-4 container-fluid mx-auto'>
					<MovieCard title='card title This is a longer card with a longer card with supporting text below  ' />
					<MovieCard title='card title' />
					<MovieCard title='card title' />
					<MovieCard title='card title' />
					<MovieCard title='card title' />
					<MovieCard title='card title' />
					<MovieCard title='card title' />
					<MovieCard title='card title' />
				</div>
				{/* Trends */}
			</main>
		</>
	);
}
