import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Header, MovieCard } from '@/components';
import { useState } from 'react';
import { SiHomeassistant } from 'react-icons/si';
import { GetServerSideProps } from 'next';

const inter = Inter({ subsets: ['latin'] });
interface Props {
	id: number;
	firstName: string;
	lastName: string;
	fullName: string;
	family: string;
	imageUrl: string;
	title: string;
}

export default function Home({ movies }: { movies: Props[] }) {
	const [mode, setmode] = useState('light');
	const toggleMode = () => {
		if (mode === 'light') {
			setmode('dark');
			document.body.style.backgroundColor = '#141a4d';
		} else {
			setmode('light');
			document.body.style.backgroundColor = 'white';
		}
	};
	return (
		<>
			<Head>
				<title>Moflix | Movies | Tv Shows</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main className=''>
				<Header
					mode={mode}
					toggleMode={toggleMode}
				/>
				{/* Breadcrumbs */}
				<div className='row container-fluid mx-auto '>
					<nav
						aria-label='breadcrumb'
						className=' my-2   mx-auto'
					>
						<ol className='breadcrumb'>
							<li className='breadcrumb-item'>
								<a href='#'>
									<SiHomeassistant />
								</a>
							</li>
							<li className='breadcrumb-item'>
								<a href='#'>Movies</a>
							</li>
							<li
								className='breadcrumb-item active'
								aria-current='page'
							>
								Trending
							</li>
						</ol>
					</nav>
				</div>
				{/* Featured */}
				{/* Recent */}
				<div className='row row-cols-1 row-cols-sm-2  row-cols-lg-5 row-cols-md-3 g-4 container-fluid mx-auto'>
					{movies.map((m) => {
						return (
							<MovieCard
								key={m.id}
								title={m.fullName}
								imageUrl={m.imageUrl}
								badge={m.family}
								chair={m.title}
								id={m.id}
							/>
						);
					})}
				</div>
				{/* Trends */}
			</main>
		</>
	);
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	// Fetch data from external API
	const res = await fetch(`https://thronesapi.com/api/v2/Characters`);
	const movies = await res.json();
	return {
		props: { movies }, // will be passed to the page component as props
	};
};
